### ISSUE TITLE
GameServices receiving data without update on broker

### ISSUE THREAD

**Issue by makoeta** [DigKick/DigKick#24]
**Describe the bug**
The frontend gameService triggers the callback from the broker multiple times.

**To Reproduce**
1. Start backend, broker and frontend
2. Publish a test game via Postman (or else) -> publish register obj to topic: /table/register

```json
{
    "name": "test"
}
```

3. Go to localhost:4200
4. Open console
5. Click on "VIEW"
6. See multiple packages received by the client

(We should open an extra ticket on deleting the logs and using winston or something else for it)

**Expected behavior**
Receiving data ones on click and than just if the game data changes.

**Comment by hiqs-chris** [comment]
Maybe fixes #35

**Comment by d3473r** [comment]
Fixed by https://github.com/DigKick/DigKick/pull/50
