### ISSUE TITLE
Player name is not displayed correctly after initial change

### ISSUE THREAD

**Issue by hiqs-chris** [DigKick/DigKick#35]
**Describe the bug**
When an new user is registered he can change its name. When he does that it is changed in the DB but the frontend displays the original name. 

**To Reproduce**
1. Sign in with a new RFID chip
2. Change the generated name to a custom one
3. Name is shortly displayed correctly -> changes back to the generated one after a short period of time

**Expected behavior**
The custom name should stay displayed!

**Additional context**
It seems like to happen only with new users.

**Comment by makoeta** [comment]
Maybe this is already fixed since @d3473r solved a lot of signal issues in the frontend?

**Comment by d3473r** [comment]
Fixed by https://github.com/DigKick/DigKick/pull/57
